### ISSUE TITLE
[Bug]:  Indexed messages: JSON formatted messages are not displayed

### ISSUE THREAD

**Issue by rubalv96** [iotaledger/explorer#105]
## Bug description

Those messages that have an indexation payload with a data field in json format are not being displayed correctly.

## Expected behaviour

![image](https://user-images.githubusercontent.com/36295331/151030997-be6c2934-58b7-4888-9ba8-7dc9843dd6ed.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/36295331/151031043-74499d07-c0dd-454e-87aa-22da0eda8e22.png)

**Comment by laumair** [comment]
Closed with https://github.com/iotaledger/explorer/pull/102
