### ISSUE TITLE
DID: Restore the search engine dedicated exclusively to DID search

### ISSUE THREAD

**Issue by rubalv96** [iotaledger/explorer#106]
## Description
The DID page does not show a dedicated search engine for DID messages, just an example.

## Motivation
The current explorer has a dedicated search engine for DID messages. It would be a good idea to bring that search engine back to the new Explorer.

## Are you planning to do it yourself in a pull request?

Yes

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/101
