### ISSUE TITLE
Message tree (navigator)

### ISSUE THREAD

**Issue by rubalv96** [iotaledger/explorer#108]
## Description

Adding a message navigator represented in the form of a tree can allow better navigation between messages to get the data without having to go from one page to another.

![image](https://user-images.githubusercontent.com/36295331/151221095-463baf2c-423a-4ce1-a867-76e4d319c641.png)

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/107
