### ISSUE TITLE
Json Viewer:  Break long strings

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#113]
## Bug description

In Json Viewer long string overflows an element's box. 
Linked to: #102 

## Steps To reproduce the bug

1.  Search for message with id: aa8bc49c0e4bb2d1f509c1544b43b12ecfd27c0cc3c29f9faa555f799e4225ff
  or navigate to ` {host}/mainnet/message/aa8bc49c0e4bb2d1f509c1544b43b12ecfd27c0cc3c29f9faa555f799e4225ff`

## Expected behaviour
Break a long string and make it continue on the next line.

![image](https://user-images.githubusercontent.com/52735957/152312409-ee39f988-f200-4cd0-9cf6-f3f1bf63d11d.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/152312192-0fe7c54c-c128-4510-8174-11f6953b6a91.png)

**Comment by rubalv96** [comment]
This has been resolved in d50c019ad2004642bc00c39b1834c4736a951f75
