### ISSUE TITLE
[Bug]: Toggle the advanced button in transaction message scrolls to message tree

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#118]
## Bug description

Toggle the advanced button in transaction message scrolls to message tree

## Node.js version

Which version of Node.js are you running?

- Node.js version:

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. 
2. 
3. 

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by laumair** [comment]
Closed with https://github.com/iotaledger/explorer/pull/120
