### ISSUE TITLE
[Task]: Add mana decay balance to address page

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1199]
### Task description

Depends on https://github.com/iotaledger/inx-chronicle/issues/1361
At the moment we display the decayed stored mana balance, but it would be good showing the stored mana (undecayed) and the decay (stored - decayed stored) so users can see the total decay of an address. 
After we can get this decay of the stored mana, the mana balance breakdown should be like
- Stored
- Decay
- Potential
- ...
Where total = stored - decay + potential + ....

please note that if an address is the address of an output, we need to calculate the decay of the output too and apply the necessary changes

**Comment by VmMad** [comment]
`Service Unavailable` At the moment
