### ISSUE TITLE
Option to hide node-api and fetch over api

### ISSUE THREAD

**Issue by no8ody** [iotaledger/explorer#12]
## Description

The Explorer offers the possibility for users to track their TX, furthermore it has many other features. When using the explorer, however, the client will fetch the balance and thus a direct community between users <-> node is performed. This should be adjustable by an option.

## Motivation

As operator of an Explorer I would like to make it available to the community, but not that the URL of my node(s) becomes public. Therefore there should be a switch in the configuration that allows the operator to specify whether fetching the balance and other communications should be done through the API or outsourced through the client (faster).
This gives everyone the possibility to protect his private node from the public or to have more speed in the queries, because the node is accessed directly by the user.

## Requirements

Write a list of what you want this feature to do.

1. Create a switch to hide the node via the config
2. Fetch the Balance via the API (if node url is hidden) or via the client

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
This is now implemented https://github.com/iotaledger/explorer/commit/0c81c4d80ddb0f105117806739f608bdf7f89231
