### ISSUE TITLE
[Task]: Update all new info texts

### ISSUE THREAD

**Issue by laumair** [iotaledger/explorer#124]
### Task description
TBD

### Requirements
TBD

### Acceptance criteria
TBD

### Creation checklist
- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
We have _clickables_ to show info modals in the following places:
- Indexation Payload
- Milestone Payload
- Transaction Payload
- Identity Resolver: welcome page
- Identity Resolver: general
- Identity Resolver: content (maybe we should also add the history?)
- Address page: main header
- Address page: general
- Address page: transaction history
- Index message: main  header
- index message: general
- message page: main header
- message page: general
- message page: metadata
- message page: tree

We can add or remove, but we should check where it makes sense to have these info popups and gather the texts that go inside

**Comment by laumair** [comment]
@lucas-tortora will provide us with the a list for all the topics

> We have _clickables_ to show info modals in the following places:
> 
> * Indexation Payload
> * Milestone Payload
> * Transaction Payload
> * Identity Resolver: welcome page
> * Identity Resolver: general
> * Identity Resolver: content (maybe we should also add the history?)
> * Address page: main header
> * Address page: general
> * Address page: transaction history
> * Index message: main  header
> * index message: general
> * message page: main header
> * message page: general
> * message page: metadata
> * message page: tree
> 
> We can add or remove, but we should check where it makes sense to have these info popups and gather the texts that go inside

**Comment by Thoralf-M** [comment]
![image](https://user-images.githubusercontent.com/46689931/155775618-744318bf-cb77-49af-bb62-089e0c1cc54e.png)
The general info button on the address page shows the `Messages in Tangle` info text

**Comment by lucas-tortora** [comment]
@laumair ,  here's most of the info.  I've got some doubts on the "general" ones, whenever you have a moment please get in touch with me through slack and we can try and clear them up.  

* __Indexation Payload__
	* __link__: https://wiki.iota.org/learn/about-iota/messages#indexation-payload
	* __text__: "The concept of the payload allows for the addition of an index to the encapsulating message, as well as some arbitrary data. Nodes expose an application programming interface that enables the querying of messages by the index. Index payloads may also be contained within a transaction payload."

* __Milestone Payload__
	* __link__: https://wiki.iota.org/learn/about-iota/messages#milestone-payload
	* __text__: "A milestone payload contains the Milestone Essence, which consists of the actual milestone information (like its index number or position in the tangle), which is signed using the Ed25519 signature scheme. It uses keys of 32 bytes, while the generated signatures are 64 bytes."

	There is more text, but given that it's for an info modal I think 1 paragraph is enough.

* __Transaction Payload__
	* __link__: https://wiki.iota.org/learn/about-iota/messages#transaction-payload
	* __text__: "A transaction payload is made up of two parts:
				1. The Transaction Essence part, which contains the inputs, outputs, and an optional embedded payload.
				2. The Unlock Blocks, which unlocks the Transaction Essence's inputs. In case the unlock block contains a signature, it signs the entire Transaction Essence part.
				"

* __Identity Resolver: welcome page__
	* __link__:https://wiki.iota.org/identity.rs/decentralized_identity
	* __text__: Decentralized Identity or Self-Sovereign Identity (SSI) defines a new method for identity management and authentication. It removes the centralized aspects and puts the Identity subject in full control over its own identity. Decentralized identity provides a solution for the increasing amount of database breaches, the lack of trust in any digital setting, and the increasingly difficult to comply to privacy legislation, such as GDPR.

* __Identity Resolver: general__
	* I'm not sure I get this one. do you mean the word general? What should it describe?

* __Identity Resolver: content (maybe we should also add the history?)__
	* __link__: https://wiki.iota.org/identity.rs/glossary#did-document
	* __text__: A set of data describing the DID subject, including mechanisms, such as public keys and pseudonymous biometrics, that the DID subject or a DID delegate can use to authenticate itself and prove its association with the DID. A DID document may also contain other attributes or claims describing the DID subject. A DID document may have one or more different representations as defined in the [W3C DID Specification Registries](https://www.w3.org/TR/did-spec-registries/)
	
* __Address page: main header__
	* __link__: https://wiki.iota.org/build/fundamentals/cryptography#addresses or https://wiki.iota.org/chrysalis-docs/guides/developer#seed-and-addresses
	* __text__: Addresses are similar to a personal account, something viewable and sendable to people you want to do business with. This personal account belongs to a seed. In the world of cryptography, a seed refers to a “private key”. Simply put, you have the seed (your private key) keeping your address (your account) safe.

* __Address page: general__	
	* I'm not sure I get this one. do you mean the word general? What should it describe?

* __Address page: transaction history__
	* __link__ : https://wiki.iota.org/iota.rs/libraries/nodejs/examples#messages-payload-and-transactions
	* __text__:  The history of all transactions for this address. Transactions are the cornerstone of value-based transfers in the IOTA network.  


* Index message: main header
* index message: general
	* Shouldn't these be the same as in the message page?

* __message page: main header__
	* __link__: https://wiki.iota.org/learn/about-iota/data-transfer#what-is-an-iota-message
	* __text__: "A Message consists of basic information that defines the type and structure of the message, and it can also contain different payloads. A payload is an attachment that can include an IOTA transaction and many other kinds of data."

* __message page: general__
	* I'm not sure I get this one. do you mean the word general? What should it describe?

* __message page: metadata__
	* __links__: 
		* https://wiki.iota.org/IOTA-2.0-Research-Specifications/2.2MessageLayout#226-metadata 
		* https://wiki.iota.org/iota.rs/specs#messagemetadata
	* __text__: In addition to a message itself, a node may store additional data that describes its local perception of a message which is not part of the Tangle ('Message metadata'). Where such metadata is defined, the metadata element names and types defined in the table in the Metadata section of the [Coordicide Specs](https://wiki.iota.org/IOTA-2.0-Research-Specifications/2.2MessageLayout#226-metadata) or [IOTA Client Library](https://wiki.iota.org/iota.rs/specs#messagemetadata)
* __message page: tree__
	* __link__: https://wiki.iota.org/learn/glossary#p
	* __text__: A message directly references up to 8 previous messages that we call its parents. As a message has parent meessages, it also has children (the messages it the parent references).
