### ISSUE TITLE
[Task]: Update DID example to a new one

### ISSUE THREAD

**Issue by laumair** [iotaledger/explorer#126]
### Task description
TBD

### Requirements
TBD

### Acceptance criteria
TBD

### Creation checklist
- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
@laumair this is solved right? I saw the new did already in `v2`

**Comment by laumair** [comment]
Correct @begonaalvarezd, will close.
