### ISSUE TITLE
[Bug]: Decentralized Identifier: deprecated DID message

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#127]
### Issue description

Message intended to inform the user that DID was created using deprecated version of identity library is not positioned correctly on the Decentralized Identifier page.

### Expected behaviour

Position the message above the General section

![image](https://user-images.githubusercontent.com/52735957/152993124-27c4f710-dda6-4b71-b425-fb88d9ea03ba.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/152984531-12153787-aaee-4949-9a03-095989fe9d40.png)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. search Decentralized identifier for DID created using deprecated version.
  ex.: did:iota:9rK6DPF46MCEzgfLD8AHFsaTuMqvmRo6kbXfjqQJPJmC

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
@brancoder this is solved right?
