### ISSUE TITLE
[Bug]: Weird display of spent transaction

### ISSUE THREAD

**Issue by domschiener** [iotaledger/explorer#129]
### Issue description

![image](https://user-images.githubusercontent.com/9785885/153236653-de110898-388f-41f1-88c5-cc9ec6204668.png)

In the address view, you can now see two transactions when funds were sent from an address. This makes it look confusing and to newcomers might seem like tokens were transferred out, but received again. 

### Expected behaviour

Display outgoing transfers last, making it obvious to the user that funds were transferred out. 

### Actual behaviour

Currently it seems like funds were sent and received 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Look at any address with transactions 

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by domschiener** [comment]
Looks like we don't order by timestamp actually?

**Comment by begonaalvarezd** [comment]
@brancoder @laumair seems like we are not really sorting by date I presume because of the dynamic txs we get after the tx history eg https://explorer-balvarez-boxfish-studio.vercel.app/mainnet/addr/iota1qzeyuqljxawaay7t3l8zrelz2qamlmraufdfqgsn2cf9f3j2fgv75nfqeq8

**Comment by laumair** [comment]
Requires API changes from chronicle which is currently in progress.

**Comment by msarcev** [comment]
Opened a PR with improvement for sorting "per page".
Sorting will still be inconsistent across multiple pages as we fetch additional data only when the user clicks on a page.
My opinion is that a lot of the code and type related to transactionHistory should be rewritten/refactored as it is complex and confusing atm (especially the whole type structure in `api/chrysalis/ITransactionDetailsResponse.ts`).
