### ISSUE TITLE
[UI]: Explorer uses custom scrollbar | Safari 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/explorer#134]
### Issue description

Safari shows a different/custom scrollbar on the explorer which offsets the page a little to the left.

<img width="348" alt="Bildschirmfoto 2022-02-09 um 22 02 53" src="https://user-images.githubusercontent.com/17240275/153289576-eeaab5ed-4c4f-4f22-b60b-4d605cf9c647.png">

Comparison explorer and `iota.org`

### Expected behaviour

Default scrollbar should be shown.

### Actual behaviour

Custom scrollbar is shown.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

macOS Monterey 12.3 Beta - Safari 15.4

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evavirseda** [comment]
This is the custom scrollbar for Explorer, it is common to all browsers. @r-c-k

**Comment by r-c-k** [comment]
Looks different (better) on Firefox for me (macOS ) @evavirseda.
<img width="103" alt="Bildschirmfoto 2022-02-11 um 20 18 06" src="https://user-images.githubusercontent.com/17240275/153655572-d23a3804-0349-4e8b-b3e9-869f72925ed6.png">

**Comment by evavirseda** [comment]
Firefox doesn't support the original design, which looks like Safari or Chrome, however, thank you for the notification

**Comment by begonaalvarezd** [comment]
We tried making the custom scrollbar compatible with all browsers but doesnt seem possible. 
Some browsers show the custom scrollbar and some the native one that comes with the browser. 
Closing issue.
