### ISSUE TITLE
[Task]: Fix unknown address

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1348]
### Task description

Address: `rms1xqqwdacty60umamke0qdxw5ats8573gvmlvezzy7gjgepnfqm8hmf0qpqgl6v2jp`
Block: `0x88f82b19d8cbc7513e6fa40b597fb62adbdc1f23fc2b550b7b7ef96cfdbc678760ad0000`
TX: `0xeb1298a2d9b1a8894c4c8c659a4ca5c48d5cc150bba61c45c6f20ef7a5afc5fc5dad0000`
![image](https://github.com/iotaledger/explorer/assets/3624944/f0e799ef-b94d-4ff5-9ca5-ba91df37ee9d)

**Comment by msarcev** [comment]
The unknown address was a restricted type. Adding back support with this https://github.com/iotaledger/explorer/issues/1359
