### ISSUE TITLE
[UI]: Missing network description 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/explorer#135]
### Issue description

The network descriptions are still placeholder texts + the legacy network placeholder refers to the "coordicide network".

<img width="1385" alt="Bildschirmfoto 2022-02-09 um 21 29 29" src="https://user-images.githubusercontent.com/17240275/153290719-69155b4d-c003-4dfb-8511-094d9f294e2e.png">

### Expected behaviour

no placeholders

### Actual behaviour

placeholders

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/195.
