### ISSUE TITLE
[Task]: Investigate what can be achieved with vivagraph params

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1358]
### Task description

Investigate what can be achieved with vivagraph params to see what shapes we can achieve.
I suggest we study the params to know what they actually do, andplay for about 1h with them to get some conclusions out of what can be tweaked, and apply it

**Comment by msarcev** [comment]
We can change the behaviour slightly, but nothing too valuable unfortunately (we can't prevent edges overlapping with param tweaks)
