### ISSUE TITLE
[Bug]: Automatic scroll down when new child is added to messages tree

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/explorer#136]
### Issue description

The message detail view automatically scrolls to the bottom when a new child is added to the messages tree. 
Testet with Safari and Firefox.

Edit: Also clicking a node in the messages tree leads to an automatic scroll (focusing the messages tree view?)

### Expected behaviour

No automatic scroll.

### Actual behaviour

Automatic scroll to the bottom.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Click on any new message from the explorer main page to see the detail view.
2. Wait until a new child is added to the messages tree.

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed with https://github.com/iotaledger/explorer/pull/156.
