### ISSUE TITLE
[Bug]: Search bar is not cleared after navigating to the result

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#140]
### Issue description

Maybe this is intended, but I found it odd that my search remained after I navigated to the result, it then remained when I was navigating about the website.

### Expected behaviour

Search bar clears after result is navigated to, search bar persists if result not found.

### Actual behaviour

Search bar persists constantly.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. search for a valid address
2. navigate around website

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Awaiting input from UI / UX team.

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/154. Got a go ahead from the design team to include it.
