### ISSUE TITLE
[Bug]: Meatball menu doesn't currently make sense next to page header

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#141]
### Issue description

On pages such as address and message there is a meatball icon next to the header. This icon on click then always opens a popup describing a message. Meatball icon is usually used to open a menu.

### Expected behaviour

Meatball Icon wasn't there, or a useful menu with options opened on click.

### Actual behaviour

Opens a pop up about messages.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. visit address page, see icon, and click
2. visit message page see icon and clic

### Errors

```shell
P.s. unable to attach screen shots to this form field as this is a code text block
```

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Should be replaced with an info icon.

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/176.
