### ISSUE TITLE
[Bug]: Information icons should not be next to 'general' header

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#142]
### Issue description

I don't think it makes sense to have an information icon next to the 'general'  header, perhaps this is supposed to be next to the page header (such as address) to replace the meatball icon.
![Screenshot 2022-02-10 at 10 00 29](https://user-images.githubusercontent.com/89913787/153383661-99196258-e726-4c4e-aa97-75f080a557c8.png)
 

### Expected behaviour

Not see an information icon next to the 'general'  header

### Actual behaviour

Icon that opens message description is next to general header
.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/176.
