### ISSUE TITLE
[Bug]: All information icons open the same popup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#143]
### Issue description

All information icons open the same popup describing messages instead of opening a popup describing the concept it is next to.

### Expected behaviour

Open popup describing the concept it is next to. i.e. if it is next to address, then the popup should describe addresses.

### Actual behaviour

All icons open popup about messages.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Duplicate of #124
