### ISSUE TITLE
[Bug]: Message ID highlighted blue, but it is not a link

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#144]
### Issue description

On the message page, the message Id is highlighted blue, but it is not a link. This is in contrast to the address page where they are not highlighted blue.

### Expected behaviour

Message Id should not look like a link, when it is not one.

### Actual behaviour

Message Id looks like a link, when it is not one.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Lets use body color for this

**Comment by laumair** [comment]
Fixed with https://github.com/iotaledger/explorer/pull/152
