### ISSUE TITLE
[Task]: Blocks of type tx not showing in slot with transaction blocks

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1440]
### Task description

eg `/alphanet/slot/32922` it says there is 1 tx, but I cant find it in the referenced blocks

It seems to be because we are not fetching all the slots in the first place, and its because of this issue https://github.com/iotaledger/inx-chronicle/issues/1362

**Comment by brancoder** [comment]
This happens because there is a bug in chronicle where each request returns the same cursor and we cant all blocks but just the first 100:
 Blocked by: https://github.com/iotaledger/inx-chronicle/issues/1362
```
 // Hardcoded to null for now because chronicle always returns the same cursor: https://github.com/iotaledger/inx-chronicle/issues/1362
cursor = null;
// cursor = response.cursor;
```

**Comment by begonaalvarezd** [comment]
Chronicle has been updated with the fix
