### ISSUE TITLE
[Bug]: Theme icon button looks like settings cog in darkmode.

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#145]
### Issue description

When in lightmode, the theme icon is a moon that looks consistent with other websites. When clicked and we are now in dark mode it transitions to a sun (which could represent lightmode), but unfortunately it looks like a settings cog.

### Expected behaviour

Theme icon is consistent with other websites, and doesn't look like a settings cog in any states.

### Actual behaviour

Theme icon in darkmode looks like settings cog.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. switch to darkmode

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Should be discussed with UI / UX team.
