### ISSUE TITLE
[Task]: Fix race condition in search

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#1463]
### Task description

If you search for `0x5f73f9666cc25bbbf553d71ff73034a61cb3f089214ff530c5b2909f35fce341ed680000` it sometimes finds a slot, when in reality is a tx

**Comment by brancoder** [comment]
Needs a chronicle bug fix: https://github.com/iotaledger/inx-chronicle/issues/1387

**Comment by brancoder** [comment]
fixed with chronicle PR https://github.com/iotaledger/inx-chronicle/pull/1388
