### ISSUE TITLE
[Bug]: Not clear what qr is for.

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#147]
### Issue description

On the address page it is not clear what the QR is for as it does not have an associated header.

### Expected behaviour

Has a header describing what it is or a call to action describing user to scan it for a particular reason.

### Actual behaviour

Floating QR code

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Should be discussed this with UI / UX team.

**Comment by laumair** [comment]
Update: We should probably have a label for the QR.

**Comment by laumair** [comment]
![Screenshot 2022-02-23 at 15 07 05](https://user-images.githubusercontent.com/20437468/155510282-af3c9b0d-9e41-4b3c-ba17-8000de32fcc2.png)
