### ISSUE TITLE
[Bug]: Theme icon could be right aligned

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#149]
### Issue description

On larger screens it seems odd for the theme icon to be left aligned and next to the search bar. Maybe we could right align this so it's in an intuitively consistent place as other websites.

### Expected behaviour

Theme icon button on the right.

### Actual behaviour

Theme icon button in the middle next to search bar.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/155
