### ISSUE TITLE
[Task]: Hide searchbox in identity resolver for non compatible networks

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#151]
### Issue description

If network is not compatible with the identity resolver, I think we should not display the search input
![image](https://user-images.githubusercontent.com/3624944/153429337-b417286a-aefb-401e-b115-f1e60bc969fc.png)

### Expected behaviour

No search box if not compatible

### Actual behaviour

search box appears even when the network is not compatible

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

`<url>/legacy-mainnet/identity-resolver/`

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Done in https://github.com/iotaledger/explorer/pull/157
