### ISSUE TITLE
[Bug]: CSS message comparison missing in Identity Resolver

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/explorer#158]
### Issue description

Message comparison is not working in the history section of the Identity Resolver tool.

### Expected behaviour

Difference between messages should be highlighted (see live explorer). 

### Actual behaviour

No difference is hightlighted.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Open Decentralized Identifier.
2. Click `DID Example`.
3. Click `load History`.
4. Click `compare with`.
5. select any message.
6. The comparison view doesn't work.

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eike-hass** [comment]
The changed lines have little gray crosses in front of them, which is very subtle. 
![image](https://user-images.githubusercontent.com/3441319/153562902-96c30e23-dc5c-488d-8c95-82ad25077575.png)
I also believe that could more obvious.

**Comment by begonaalvarezd** [comment]
So it does work but is just a matter of highlighting more the `+` right @eike-hass?

**Comment by eike-hass** [comment]
yes, the diffing is working. This is just a visual "bug", if at all. Attached screenshots of the same diff in the old and new explorer:
 
![image](https://user-images.githubusercontent.com/3441319/153844099-24a62acd-5274-4082-828d-40467d65ab53.png)

![image](https://user-images.githubusercontent.com/3441319/153844376-71b3c0bb-173f-4062-bac8-86ca5fb72a3f.png)

Notice the red and green highlight in the old explorer.

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/issues/158.
