### ISSUE TITLE
[Bug]: `Raw/Normal` Button titles are swapped.

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/explorer#159]
### Issue description

The titles of the `Raw/Normal` toggle button in the history section of the Identity Resolver tool should are swapped. Renaming these buttons to `Doc` and `Msg` is also more accurate in my opinion (see live explorer).

### Expected behaviour

When `Normal` is selected the `Normal` message should be displayed.

### Actual behaviour

When `Normal` is selected the `Raw` message is displayed.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Open Decentralized Identifier.
2. Click DID Example.
3. Click load History.

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/issues/159
