### ISSUE TITLE
[Bug]: Hyperlink for the Milestone not correct visualized

### ISSUE THREAD

**Issue by hristo-mavrodiev** [iotaledger/explorer#161]
### Issue description

It should be highlighted the `Milestone 2487678 ` in blue,  because it's a hyperlink to that milestone, not just` Milestone`

https://media.discordapp.net/attachments/941010357462397009/941622828904640583/20220211_111226.png

### Expected behaviour

should be highlighted the `Milestone 2487678 ` 

### Actual behaviour

highlighted only the `Milestone ` 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Click on a random message link

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/167
