### ISSUE TITLE
[Bug]: Search for Ed25519 Address

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#165]
### Issue description

Searching for Ed25519 Address navigates to malformed non-existent route instead of correct address route.

### Expected behaviour

Navigate to correct Address page if found.

### Actual behaviour

App navigates to malformed urll: 
`/mainnet//0645badfc713a470f01490fa23de6be9af1d294b2b53b762e8f1ee4cbd1d82a6`

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Input Ed25519 Address in search field.  ex. 0645badfc713a470f01490fa23de6be9af1d294b2b53b762e8f1ee4cbd1d82a6
2. App navigates to `/mainnet//0645badfc713a470f01490fa23de6be9af1d294b2b53b762e8f1ee4cbd1d82a6`

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed with https://github.com/iotaledger/explorer/pull/169
