### ISSUE TITLE
[Bug]: Address page: 1. and 2. tsx history pages display the same transactions

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#166]
### Issue description

On Address page same history transactions get displayed on first and second page. 

### Expected behaviour

Each page should display correct transactions.

### Actual behaviour

First and second page display sametransactions.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Navigate to Address page ex. [Link](https://explorer-balvarez-boxfish-studio.vercel.app/mainnet/addr/iota1qrp7wn7ag964yh7r6csphg8l47q9ehlpxz8tukhad09x7avjj09s5qunq87)
2. Navigate between 1. and 2. page in transaction history 

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/170
