### ISSUE TITLE
[Task]: Limit payload data height

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#179]
### Issue description

If there is an indexation payload with JSON it highlights it as show in the image, but when its large JSON payload you have to scroll and scroll, its shows it all, would be better with a max height

![image](https://user-images.githubusercontent.com/3624944/154680032-6ef61fd9-410a-48fe-a1d1-da842a6bf2e5.png)

### Expected behaviour

Set a max height of eg 400px and a scrollbar when needed

### Actual behaviour

Payload takes up too much vertical space from the page  

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/197.
