### ISSUE TITLE
[Task]: Remove caption or display "no children" in message tree if there are no children

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#180]
### Issue description

 If a message has no children it would be better to either remove the caption or display "no children"
![image](https://user-images.githubusercontent.com/3624944/154680353-08aebd26-c5a7-4772-bd84-c9924db2f4d4.png)

### Expected behaviour

TBD

### Actual behaviour

TBD

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/185.
