### ISSUE TITLE
[Task]: Line at the bottom does not match the box

### ISSUE THREAD

**Issue by laumair** [iotaledger/explorer#199]
### Task description

The bottom line on the landing page doesn't match the box width. They should be of the same size. 

![image (2)](https://user-images.githubusercontent.com/20437468/155505458-2df52533-0f56-4cc7-92a4-9e5a48c6c910.png)

### Requirements

The width of line should match the box width.

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Couldn't be reproduced on latest build.
