### ISSUE TITLE
[Task]: Remove facebook link

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#210]
### Task description

The IF deactivated the Facebook page - could we remove the link?

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/211.
