### ISSUE TITLE
Tx is in it's own children

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#22]
## Bug description

In the children list the own hash is listed
https://explorer.iota.org/mainnet/transaction/VHJQQVGUOVCMNVDQDS9DVXHFCWWFMYIXOZBRDWGXKFYLNVYXBRJQJPMT9TKP9FKJXQCRD9PSHLKDA9999

**Comment by obany** [comment]
Fixed https://github.com/iotaledger/explorer/commit/0ce6776ff133d91bdc80b23bbc9679df8bbfb588
