### ISSUE TITLE
[Bug]: Registering Network Storage Services with DynamoDb

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#243]
### Issue description

Registering network storage services for dynamoDb uses interface IMarket instead of INetwork.

Line in question:
https://github.com/iotaledger/explorer/blob/dev/api/src/initServices.ts#L156

### Expected behaviour

```
ServiceFactory.register("network-storage", () => new LocalStorageService<INetwork>(
            config.rootStorageFolder, "network", "network"));
```

### Actual behaviour

```
 ServiceFactory.register("network-storage", () => new AmazonDynamoDbService<IMarket>(
            config.dynamoDbConnection, "network", "network"));
```

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Seems to be already fixed.
