### ISSUE TITLE
[Task]: Implement design for output details page

### ISSUE THREAD

**Issue by laumair** [iotaledger/explorer#262]
### Task description

For each message displayed for stardust, we have to display the output details. 

### Requirements

Implement UI for output details. 

Link to design [here](https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=183%3A20091). 

### Acceptance criteria

As the search is also working now, the data should not be mocked and it should be hooked up with the actual API. 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Will complete this task when we update support for other output type. Should be easy now that the rest is ready.

**Comment by laumair** [comment]
Will keep this opened for now as the designs are slightly changed.
