### ISSUE TITLE
Add a JSON Viewer Component to provide syntax highlighting

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/explorer#27]
## Description

A JSON viewer component that can provide syntax highlighting can be helpful when debugging transactions or channels. 

## Motivation

Improved visual content for users

## Requirements

1. Just syntax highlighting with colors aligned with the look and feel of the Web Application 

## Are you planning to do it yourself in a pull request?

Yes

**Comment by obany** [comment]
Added e3e468aa0ed3fccbf83a4a9f2e3dfb6162b744cc
