### ISSUE TITLE
Explorer does not render in Safari

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/explorer#28]
## Bug description

Using Safari Version 13.1.3 (15609.4.1) Explorer does not render (a blank page is displayed). Same issue experienced on iPadOS versions. 

## Hardware specification

What hardware are you using?

- Operating system:
- 
- Device: Mac BookPro / iPad

## Expected behaviour

Rendered as it happens with Chrome or Firefox

## Actual behaviour

Nothing is rendered. blank page. 

## Errors

at the Safari Web Console: 

ReferenceError: Can't find variable: BigInt

**Comment by obany** [comment]
Older versions of Safari don't support BigInt https://www.caniuse.com/?search=bigint

A polyfill has been added which should allow browsers with missing BigInt support to function correctly.
