### ISSUE TITLE
[Task]: Rename Indexation Payload to Data Payload

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#283]
### Task description

Indexation payload type (chrysalis) now lives in the Tagged (arbitrary) Data that we have on payload. So let's rename it in the code and label it "Data" payload

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by laumair** [comment]
Implemented in https://github.com/iotaledger/explorer/pull/286
