### ISSUE TITLE
[Task]: Update the network selector

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#295]
### Task description

In discussion with @lzpap we concluded that we should redesign the network selector to make it clearer with the protocol development phases/networks.
So ideas to consider are:
- Swap and split the networks and "protocol" label, so that the networks are on top, and protocol used on each is visible below

New structure would be something like:
```
Legacy Mainnet | Mainnet | Devnet | Shimmer | Testnet | Alphanet
-------------------------------------------------------------------
Legacy     | Chrysalis | Chrysalis | Chrysalis | Stardust | TBD
```

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by laumair** [comment]
@msarcev @lzpap 

What are `Testnet` and `Alphanet` in the new structure? 

Also, what is the motivation behind choosing this approach rather than categorising them with IOTA network versions?

**Comment by lzpap** [comment]
What you call iota network versions are actually protocol versions, not networks. Networks are physical infrastructure, protocol is the sw running on them.

Protocol versions will come and go, move from testnet to shimmer and then further to iota, etc. But the networks will stay the same, just continuously being updated to the latest protocol versions.

**Comment by laumair** [comment]
> What you call iota network versions are actually protocol versions, not networks. Networks are physical infrastructure, protocol is the sw running on them.
> 
> Protocol versions will come and go, move from testnet to shimmer and then further to iota, etc. But the networks will stay the same, just continuously being updated to the latest protocol versions.

Fair point, all right. Thank you for the clarification.
