### ISSUE TITLE
Edges in visualizer hardly visible in Dark Mode

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/explorer#32]
## Description

The edges in the tangle visualizer (dark mode) seem to have too little contrast in comparison to the light mode, which makes them hardly visible at a first glance.

<img width="339" alt="Bildschirmfoto 2021-01-18 um 13 40 48" src="https://user-images.githubusercontent.com/17240275/104918439-0abba180-5995-11eb-9102-405c5b3d3a6a.png">

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
Fixed https://github.com/iotaledger/explorer/commit/43465248b1413bfe1f51bb57c26b9b207b0e610e
