### ISSUE TITLE
[Task]: Docs for Stardust

### ISSUE THREAD

**Issue by lzpap** [iotaledger/explorer#339]
### Task description

- Setup docs project in Explorer repo (docusaurus to be deployed with IOTA wiki)
- Write walkthrough tutorial on how to use the Explorer

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Closing in favour of https://github.com/iotaledger/explorer/issues/402
