### ISSUE TITLE
[Task]: Add balance from expired outputs

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#353]
### Task description

If an output is expired (time in the expiration unlock condition passed without it getting consumed before), then the amount of the output should be added to the balance of the return address

### Requirements

-

### Acceptance criteria

-

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by luca-moser** [comment]
For now we won't be adding this balance computation check as it would require more sophisticated computation on Chronicle's side taking in account the current time to do the calcs correctly which given the big data set handled by Chronicle, could be too heavy.

Instead, we make it more visible to the user in the associated outputs which ones have more complicated unlock conditions and add a `Conditionally Locked Balance` to the address view.
