### ISSUE TITLE
Thousands separators in the Currency Converter

### ISSUE THREAD

**Issue by thekarlw** [iotaledger/explorer#36]
## Description

If you want to know what 1 Ti is currently at Explorer.iota.org, you get for Example the result "1147270.23" USD
For the sake of clarity, it would be nice if the result were displayed as "1,147,270.23" USD or "946.125,00" EUR

## Motivation

This contributes to the simplification of the understanding and the overview

## Requirements

1. Thousands separators in the Currency Converter

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
Added with this commit https://github.com/iotaledger/explorer/commit/c6297bb496fd2d61b8a42af3af019bc130a9592e
