### ISSUE TITLE
[Task]: Harmonize extended landing page metrics

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#365]
### Task description

All landing pages which are compatible with Stardust show following extended metrics:

https://www.figma.com/file/j4RLa61iZ18VXwiabeyu9k/IOTA-Explorer-UI?node-id=128%3A53544

- Tokens created: "11.2k"
- NFTs minted: "34.6k" 
- Active addresses: "34k"
- Locked storage deposit: "549k SMR"
- Daily transactions: "10k"

### Requirements

- On non Stardust compatible networks the extended metrics are hidden and blocks are named messages
- Extended metrics are hidden if their endpoints are not available

### Acceptance criteria

- Metrics load in less than a second.

**Comment by msarcev** [comment]
![image](https://user-images.githubusercontent.com/6864498/178523376-cef1d1a2-11b2-4ee6-b03a-fad484239e27.png)
![image](https://user-images.githubusercontent.com/6864498/178523603-e5de698f-1150-4fa7-82ec-249c7ee7f175.png)
![image](https://user-images.githubusercontent.com/6864498/178523698-423a8511-e964-42a3-8d6a-5e1f657841cd.png)
![image](https://user-images.githubusercontent.com/6864498/178523785-5f4e16cd-1f94-4a9f-b415-4aa7de5ad920.png)

Visible on alphanet only currently until we wire the API up.
