### ISSUE TITLE
Show timestamp from milestone for each referenced message

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#37]
## Description

If a message got referenced by a milestone it already shows the milestone index at the top, would be nice to also have the time from the milestone there

## Motivation

Makes it easier to find out when a message was sent

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
Implemented in 03b5a40ad120c6cd0887ee1cbba8d6df622e618a

![image](https://user-images.githubusercontent.com/5030334/107967050-ef03e500-6fac-11eb-8072-0d2a5d942856.png)

**Comment by Thoralf-M** [comment]
Awesome, thanks!
