### ISSUE TITLE
[Bug]: Missing associated outputs for address

### ISSUE THREAD

**Issue by lzpap** [iotaledger/explorer#375]
### Issue description

Associated outputs don't display Basic Outputs held by the address.

Look at this transaction: https://explorer.alphanet.iotaledger.net/alphanet/block/0x37990a1b37661718e8101eb2e93dab13402c39dba2612c58ec495645914ffbd3

Everything on the output side is controlled by the address `rms1qzznep3sng85k3gwzzz884n26552hl476lqc0s3p4huj5gtudupvc7g2sdr`, so the alias, the foundry implicitly, and the two basic outputs.

When you load the address page however https://explorer.alphanet.iotaledger.net/alphanet/addr/rms1qzznep3sng85k3gwzzz884n26552hl476lqc0s3p4huj5gtudupvc7g2sdr, it shows the address owns native tokens which are in [this basic otuput](https://explorer.alphanet.iotaledger.net/alphanet/output/0x9af75ee727ea30afe917e91cf7596b46b7d296f5270732ac91f755f0ed1f98870200) but the output is not in the list of associated outputs, just like the other [basic output](https://explorer.alphanet.iotaledger.net/alphanet/output/0x9af75ee727ea30afe917e91cf7596b46b7d296f5270732ac91f755f0ed1f98870300) from the transaction.

### Expected behaviour

Associated outputs list displays all output that contain the address.

### Actual behaviour

Basic outputs in this case are not displayed.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarcev** [comment]
Fixed with https://github.com/iotaledger/explorer/pull/374
