### ISSUE TITLE
Input shows wrong address when the unlock block is wrong

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#39]
## Bug description

The addresses for the inputs are currently only derived from the unlock blocks, but when the unlock block is wrong, it also shows the wrong address for this input.

For example here https://explorer.iota.org/chrysalis/message/9d4706453a904978620326f1937fb29e289859aacbe7ebb80b87b6b0e9674a2b
The address of the first input should be atoi1qrh980fv09ts0ruaaf0mggmulxju96w7zva2yrqcn3a8muv40hlfjvxlmhr because that's the address of the output with index 1 here https://explorer.iota.org/chrysalis/message/b79f9d1fbc45467d1e198f71f7f65cd2da43b5450180e306bb59e232b41dde77

## Expected behaviour

It should show the correct address

## Actual behaviour

Shows the address from the unlock block

**Comment by Thoralf-M** [comment]
For better performance one could maybe only request it from the transaction when the unlock block is invalid?

**Comment by obany** [comment]
Updated, it now makes two passes to calculate the address for the inputs, first using the unlock block (as it already has these details as part of the message), then using secondary lookups for the outputs based on the transactionid and index. 

This also means that the redirect to look at the linked transaction message is faster, as the lookup it usually does when you click the transactions link already knows the correct message id to navigate to.

**Comment by Thoralf-M** [comment]
@obany something is wrong, it shows `atoi1qzk3t3938s2rs44ct4w5l3qv80lt4zk08dajvdvnq5rwj2s9t0skgceqpj8` as address for the inputs now, but I think it should be `atoi1qrh980fv09ts0ruaaf0mggmulxju96w7zva2yrqcn3a8muv40hlfjvxlmhr`

**Comment by obany** [comment]
It just grabs the output associated with the transaction not sure how that could be wrong, do you have another example that one has been pruned.

**Comment by Thoralf-M** [comment]
https://explorer.iota.org/chrysalis/message/35d498b73ff098cf6e3b5d528253c3ac5583aa2091cc6e54da29158c878808d5

if I look in the network tab from the browser it also get the correct output and address `a47d7c5bfaacbea099aee4f5df4226d16e9feb2e803c9484cbd87875c2db78fe` in this case (don't get confused, it's also in one output)
![image](https://user-images.githubusercontent.com/46689931/108699910-296a0680-7506-11eb-94a0-e8f22b9ab713.png)
but it seems like it does something weird with this address and converts it to `2383a15e0ce43ecdcd35a43c4b5b5d11d88c33d5284f2f80b02a70178984f58a` but I don't see how or where the `2383a15e0ce43ecdcd35a43c4b5b5d11d88c33d5284f2f80b02a70178984f58a` should come from if not from this address conversion

**Comment by Thoralf-M** [comment]
@obany it makes no sense, the first input here https://explorer.iota.org/chrysalis/message/e58284c264975c5070ac277f0c430054969f54193afff5a207d05dd1068b28ae shows `e05a3d98cf87c39b0fb0788b394eff0a040011f945280f35a99173a4dccc3bf5` as address, but if I open the message for this input there is no output with this address and both messages also don't have an unlock block with this address

**Comment by obany** [comment]
OK got it, fixed with this commit https://github.com/iotaledger/explorer/commit/888931651f138ed05cba34395d16f5932871fd4d#diff-210ae16ea9f030dbba00fa4a2a8812a19aa3a09ea8cf8f4f9b97981eb5df4077L116

It was doing an unnecessary conversion on the address which was already in the correct format.

**Comment by Thoralf-M** [comment]
Thanks!

**Comment by tscharlii** [comment]
Looks fine to me, too. I originally reported the issue on discord a few days ago. Thoralf-M kindly created the issue here on my behalf.
