### ISSUE TITLE
Add a Summary at the Top of Every Value Message

### ISSUE THREAD

**Issue by Oskar-F** [iotaledger/explorer#41]
## Description

Add a summary at the top of every value message, to make the explorer more accessible for the average user.

## Motivation

The explorer is not very user-friendly, especially for simple value transfers. The average user is confronted with many technical terms and information, that they might not understand.

## Requirements

At the very top of the message page, add a distinct box with a short summary of the most important information about the message, such as:

- Sent from (address) (possibly colored red)
- Sent to (address) (possibly colored green)
- Amount transferred
- Status (colored appropriately)

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
Simplified view is now implemented by default.
