### ISSUE TITLE
[Task]: Change visualizer to show squares

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#411]
### Task description

Given that we call messages now blocks, it would be nice if the visualizer shows the vertices as squares as to better reflect the name "block". The node dashboard already displays them this way.

### Requirements

- The circles should be displayed as squares.

### Acceptance criteria

- Squares, no circles.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
Maybe https://github.com/iotaledger/explorer/issues/58 can be done at the same time if the two gets a shared module or something like that?
