### ISSUE TITLE
Allow users to switch between simple and advanced interface.

### ISSUE THREAD

**Issue by Magelis86** [iotaledger/explorer#42]
Using the IOTA explorer might be too complex for the standard user. There are way too many infos when looking at a given transaction :

Like people are saying on Reddit : '_When I make a transaction, why do I have to decipher this endless information on this page to get the basic information every normal enduser needs to see? I don't need parent messages (1-4), I don't need nonce, I don't need an ED25519 address, I don't need two separate sections about input/output filled with information 99% of the users (me including) don't understand, I don't need indexation payload (ok cool), I don't need child messages, what are even messages? I send MIOTA not a text message (yeah just a joke).'_

I think that by defaut, the Explorer should be on a basic mode only displaying essential infos (From, To, Amount, Status).

Want more? Put on the upper corner an 'Advanced mode' button allowing to switch between the 'Idiot proof' interface and a more complex interface (the one that we currently have).

Just my idea.

Cheers!

**Comment by obany** [comment]
Simplified view is now implemented by default.

**Comment by Magelis86** [comment]
Great thanks!
