### ISSUE TITLE
[Bug]: Last / Target display incorrect

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/explorer#427]
### Issue description

If the Last / Target: is near at 4s / 5s and the website gets reloaded the counting sometimes starts with 6s, 7s till 10s.

![image](https://user-images.githubusercontent.com/71659397/181488334-f44dfdfd-7f77-48ee-8f58-f54571136ce1.png)

### Expected behaviour

Counter should not exceed 5s in normal milestone issuance interval

### Actual behaviour

Counter exceeds 5s in normal milestone issuance interval

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Wait until the counter is at 4s / 5s
2. Reload page
3. Counter counts till 10s

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luca-moser** [comment]
Detach the logic to update the counter away from the milestone timestamp.
