### ISSUE TITLE
[Task]: Support latest versions of node in Explorer

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#439]
### Task description

Explorer has errors when trying to `npm i` with node `> 16.4` 

- Fix the dependencies so we can use newer versions of node/npm

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by luca-moser** [comment]
- Try out whether updating/defining specific module versions would fix the problem
- Find out if there is a way to maybe define on package.json level to treat the dependencies without checking upstream conflicts
- If no solution was found, we just add a note to the READMe that installing with node >16.4 needs special `npm install` flags.

**Comment by msarcev** [comment]
Fixed the client package.json so that it works with node `16.16` LTS.
For node 18 many more packages were breaking, not worth it atm.
