### ISSUE TITLE
Add labels to associated outputs

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#447]
As a token holder, I want to see whether an output has any special unlock conditions at a glance, so I can derive which ones are more complicated and are part of the `Conditionally Locked Balance`.

Acceptance criteria:
- There are icons and labels for `Storage Deposit Return Address`, `Expiration`, `Timelock`.
  - Icons:
    -  SDRUC: back arrow
    - Expiration: hourglass
    - Timelock: clock
  - Label values:  
    - SDRUC:  Amount to return.
    - Expiration: In "2 hours", "5 days".
    - Timelock: Until "2 hours", "5 days".
- Use a separate column `Conditions` to display the labels and in the card view as a new line break.

**Comment by abbasabid** [comment]
@luca-moser As there was not enough space in Associated outputs table to add a new column for Special Conditions we have decided to show the icons with output ids in first column and display the data in the tooltip. This is how it will show now:
<img width="1499" alt="Screenshot 2022-08-30 at 3 14 11 PM" src="https://user-images.githubusercontent.com/101638386/187412071-24bd0f03-7b98-46f2-a2f2-7a0e5ea6cedb.png">

**Comment by luca-moser** [comment]
Looks great. Could we perhaps also remove the "Output" form "Basic Output" everywhere given that it is clear that the list items are outputs, so "Output" is redundant in that sense.

![Screenshot 2022-08-30 at 12 28 46](https://user-images.githubusercontent.com/1385611/187414535-ef709d4f-f007-451e-ba02-1c8a14a8c292.png)

**Comment by abbasabid** [comment]
Sure.
