### ISSUE TITLE
Fix high request count on address with large history

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#473]
Accessing https://explorer.shimmer.network/testnet/addr/rms1qzpf0tzpf8yqej5zyhjl9k3km7y6j0xjnxxh7m2g3jtj2z5grej67sl6l46 causes the tab to essentially freeze as the frontend code tries to do a gazillion of requests against the backend:

https://user-images.githubusercontent.com/1385611/185230907-17b49e3e-8ec6-40e0-bd62-86ab06ef9363.mp4

**Comment by msarcev** [comment]
Example address on testnet `rms1qzpf0tzpf8yqej5zyhjl9k3km7y6j0xjnxxh7m2g3jtj2z5grej67sl6l46`
