### ISSUE TITLE
Fix weird artefacts in payload filter

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#477]
Sometimes weird artefacts are shown within the checkboxes of the payload filter on the landing page feed:

![Image](https://user-images.githubusercontent.com/1385611/186842022-843c9053-4e4d-4863-a206-2221b224897d.png)

**Comment by brancoder** [comment]
Closed the issue as we cant reproduce it but we will keep monitoring and reopen if it happens again.
