### ISSUE TITLE
Add placeholder statistics page

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#478]
As a token holder, I want to see graphs/charts of network metrics over a period of time, so I can asses network growth.

Charts:
- Daily #:
  - of transactions
  - of active addresses
  - of iota/shimmer transferred
  - of blocks
- Total:
  - per block payload type 
  - distinct native tokens (not supply count but how many unique native tokens there are)
  - nfts minted
  - tokens used for storage

A daily chart would look like this:

![Image](https://user-images.githubusercontent.com/1385611/185337777-4d11181b-9df0-4465-aa2a-62a5203750b1.png)

while a total would represent the total over the period of time:

![Image](https://user-images.githubusercontent.com/1385611/185337860-d11f574f-727a-48f9-97e6-9c61394e4245.png)

Acceptance criteria:
- Charts can be zoomed in and out/timeframe can be narrowed.
- Charts must load with data from the beginning of recording.
- Charts must load in under 5 seconds.

**Comment by msarcev** [comment]
- Add a new page under Utilities called `Statistics`
- Add `chart.js` as dependency (so we can move away from chartist at some point)
- Try to use `charts` to render a graph like above with hardcoded data (for now)

**Comment by msarcev** [comment]
Let's merge this but hide the page for now (make it unreachable).
