### ISSUE TITLE
[Request]: Show staking information in the explorer

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/explorer#493]
### Task description

At the moment it is not possible to see the staking rewards and participation per address in the explorer. It would be great to include the staking rewards and the participation per address.

Statistics about the top staked addresses and the total staked iota amount would also be interesting.

### Requirements

1. Show staking per address
2. Show participation per address
3. Show statistics about top staked addresses and total staked iota

### Acceptance criteria

1. Show staking per address
2. Show participation per address
3. Show statistics about top staked addresses and total staked iota

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
@luca-moser Wdyt about this ? Staking stats on chrysalis.

**Comment by luca-moser** [comment]
I am not sure we want to implement a per address view of how much it is staking/participating for now. A view for the ongoing votes and staking events might be something we want to look into but it doesn't have any priority right now.

**Comment by msarcev** [comment]
Closing as stale.
