### ISSUE TITLE
[Epic]: Add ability to download TX history

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#496]
As a token holder, I want to export the tx history of an address, so I can create an overview for my taxes.

Acceptance criteria:
- Should work only on a single address.
- Able to select output types to include in the export and or "simple transfers".
- There is a cap configurable by the deployer of the explorer on the max # of entries for an export.
- Can not select a range which is outside the underlying Chronicle's history.
- Columns: date (ISO8601),  tx-id (hex), output type (basic, alias, foundry, nft), amount (+/-)
- Formats(?): select between CSV and JSON

Split into: 
https://github.com/iotaledger/explorer/issues/548
https://github.com/iotaledger/explorer/issues/579

**Comment by msarcev** [comment]
@luca-moser "Simple transfers" meaning like basic output with just AUC ? So just sending SMR around, right ?

**Comment by msarcev** [comment]
Do we need a date range filter ? Past week, past month etc...

**Comment by luca-moser** [comment]
- Yes, so simple transfers are those with just a AUC. 
- For the range selection those should just be typical date selectors.
![image](https://user-images.githubusercontent.com/1385611/194877975-b541a961-038d-46c2-ae9d-f4322a4ed428.png)
