### ISSUE TITLE
[Task]: Pause live feed when hovering on an message

### ISSUE THREAD

**Issue by no8ody** [iotaledger/explorer#50]
## Description

For a better live feed experience, it would be nice if the live feed stopped when moving over an address. Especially with many MPS it becomes almost impossible to pick a message out of the feed.

**Comment by Thoralf-M** [comment]
There is now a pause button at the top right
![image](https://user-images.githubusercontent.com/46689931/181747919-adedcd64-f994-452a-aa9a-35797c4877fd.png)
