### ISSUE TITLE
Fix tag opening a blank page on block page.

### ISSUE THREAD

**Issue by abbasabid** [iotaledger/explorer#527]
**Task description**
On clicking on the Tag in Tagged Data Payload on block page it leads to the page with no content.

**Requirements**
N/A

**Acceptance criteria**
Disable the click on tag in tagged data payload.

**Creation checklist**
 I have assigned this task to the correct people
 I have added the most appropriate labels
 I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Needs eslint fix from https://github.com/iotaledger/explorer/pull/537
