### ISSUE TITLE
Fix % SMR claimed metric

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#584]
Currently the "Rewards claimed" metric on the Shimmer page is wrongly calculated by using the total supply of SMR instead of excluding the 20% allocated to TEA & community treasury.

Initial supply: 1'450'896'406 SMR
25% increase: 362'724'101.5 SMR
Total supply: 1'813'620'509 SMR

So today the claimed % is actually ~60% not 48%.

**Comment by msarcev** [comment]
Hey @shufps, can you update the config for this please when you catch a moment ?

**Comment by shufps** [comment]
![image](https://user-images.githubusercontent.com/3079832/203795692-8bc5b306-3479-4ea2-811b-6f44486bbfd1.png)

DynamoDB-screenshot confirms, there is nothing wrong with the supply in the config :man_shrugging:

**Comment by shufps** [comment]
according to:
```
In total, 1,450,896,407,249,092 glow (~1,450,896,407 SMR) is allocated to IOTA Stakers in the Shimmer genesis snapshot.
```

I changed the config for all explorers to `1450896407249092 glow` for the Shimmer network
