### ISSUE TITLE
[Bug]: Expired Native tokens

### ISSUE THREAD

**Issue by wireless90** [iotaledger/explorer#594]
### Issue description

Someone sent me 1000 dodge. I did not claim it. It expired. I viewed the address in explorer, seems like the 1000 dodge is still with me.

Over here, https://explorer.shimmer.network/shimmer/addr/smr1qqe0adqtuyz2pg4gqf37cu9w0d4znj4dejzz6svw3fhtsmgw08j3g4pgs5a

i have an address which contains 1000 native tokens of DODGE sent by someone.
Seems like the expiration timer was hit. 
Here is the tx,
https://explorer.shimmer.network/shimmer/transaction/0x823dd3b77ff631713a1f5aee4f6bdef6eb17016e039b097e2e494f8254965bd0

This the in output,
https://explorer.shimmer.network/shimmer/output/0x823dd3b77ff631713a1f5aee4f6bdef6eb17016e039b097e2e494f8254965bd00000

We can see that it expired 2 months ago, why do i still have the 1000 dodge, i expected it to get sent back

Unsure if it is linked to this  #353 

### Expected behaviour

Expected upon expiration timer, the 1000 dodge would get sent back along with the storage deposit.

### Actual behaviour

"Looks" like the 1000 dodge is still with me.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brancoder** [comment]
Possible solution is to utilize the indexer filtering parameters `hasExpiration` and `expiresAfter`, when fetching outputs, to only retrieve still relevant outputs for the Address
