### ISSUE TITLE
Wrong unlocks displayed in tx payload

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#655]
Given this example transaction: https://explorer.alphanet.iotaledger.net/alphanet/block/0x7429b2a997a439b67a657695a3735077c2873d32a4b4a49e45f02517f26d9152

it displays has having N amount of times a `SignatureUnlockCondition`:

![Image](https://user-images.githubusercontent.com/1385611/215774812-ec90fb50-07e4-40ff-b40e-5b81c20a3a84.png)

However, this wouldn't even be possible protocol spec wise. It doesn't show the reference unlocks which are actually occurring within the tx (this is a `/api/blocks/<:id>` response):
```json
    "unlocks": [
      {
        "type": 0,
        "signature": {
          "type": 0,
          "publicKey": "0x875f0e979783122b65795764222db3ee78541729774737d07aa661b6f6a85b96",
          "signature": "0x2bfd8394d12211829633b9b88ef67774b29675f6e77127c2850719e9db1091de396264c4a5b64fc2a37d384a75bd1b5386a63e34c0915282dc6e4a3a6d7e3001"
        }
      },
      {
        "type": 1,
        "reference": 0
      },
      {
        "type": 3,
        "reference": 0
      },
      {
        "type": 3,
        "reference": 0
      },
      {
        "type": 3,
        "reference": 0
      },
      {
        "type": 3,
        "reference": 0
      }
    ]
```

**Comment by msarcev** [comment]
- Handle all 4 unlock type in the `Unlocks` component
Something like this fields/design wise:
![image](https://user-images.githubusercontent.com/6864498/216984647-8b490b02-4b7e-4974-82e7-f6b08ec8b24d.png)
