### ISSUE TITLE
[Task]: Profile slow API routes used in Explorer pages

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#663]
### Task description

We need to assess Explorer pages that take more than 2sec to load completely, so that we can identify the problematic API requests.

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by abbasabid** [comment]
Following are the Explorer pages i found which have slow api routes:

**Address Page:**
* Ed25519 Address: `rms1qzpf0tzpf8yqej5zyhjl9k3km7y6j0xjnxxh7m2g3jtj2z5grej67sl6l46`
* It took approx 30 sec to load this page completely
**Transactions section**
**API:** transactionHistory api 
**Duration:** 7 sec
**Native tokens section** 
**API:** aliasOutputDetailsByAddress api 
**Duration:** 28 sec
**Nfts section** 
**API:** nftOutputDetailsByAddress api 
**Duration:** 28 sec
**Associated outputs section** 
**API:** associatedOutputs api
**Duration:** 14 sec

**Transaction Page:**
* Transaction id: `0x8acde935b33c5315bdc2dd549ed0d9da2926c43ad50d4fa3a68a756494a5a9d3`
* Duration to load page completely is approx 20 sec.
**Payload Section**
**API:** transactionIncludedBlock api
**Duration:** 20 sec

**Comment by abbasabid** [comment]
> Following are the Explorer pages i found which have slow api routes:
> 
> **Address Page:**
> 
> * Ed25519 Address: `rms1qzpf0tzpf8yqej5zyhjl9k3km7y6j0xjnxxh7m2g3jtj2z5grej67sl6l46`
> * It took approx 30 sec to load this page completely.
> * **Transactions section**
>   **API:** transactionHistory api
>   **Duration:** 7 sec
> * **Native tokens section**
>   **API:** aliasOutputDetailsByAddress api
>   **Duration:** 28 sec
> * **Nfts section**
>   **API:** nftOutputDetailsByAddress api
>   **Duration:** 28 sec
> * **Associated outputs section**
>   **API:** associatedOutputs api
>   **Duration:** 14 sec
> 
> **Transaction Page:**
> 
> * Transaction id: `0x8acde935b33c5315bdc2dd549ed0d9da2926c43ad50d4fa3a68a756494a5a9d3`
> * Duration to load page completely is approx 20 sec.
> * **Payload Section**
>   **API:** transactionIncludedBlock api
>   **Duration:** 20 sec
