### ISSUE TITLE
[Bug]: Search returns wrong address

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#685]
### Issue description

`smr1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqy8f002` is an ed25519 address, but the explorer returns the alias address that encodes the null address

### Expected behaviour

Should return the bech32 address, so https://explorer.shimmer.network/shimmer/addr/smr1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqy8f002

### Actual behaviour

Opens https://explorer.shimmer.network/shimmer/alias/smr1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmve2j5

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Search for smr1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqy8f002

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarcev** [comment]
Seams to not be the case anymore on newer version.
