### ISSUE TITLE
Visualizer related transactions color

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#727]
I would like to get another color in the visualizer for reattached transactions and/or highlight all blocks with the same tx id if one clicks on one of them

With the EVM chains they send multiple blocks with the same transaction where many blocks are shown as conflicting

If such a change would make the performance a lot worse then it's not worth it to implement and please close this issue

**Comment by msarcev** [comment]
When a transaction is selected, we will show a list in the metadata block on the top/left displaying other blocks with the same transactionId and the status of each (confirmed, pending, conflicting...)
