### ISSUE TITLE
Tooltip for referenced/confirmation rate

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/explorer#74]
## Description

Add a tooltip to the referenced/confirmation rate that explains how a confirmation rate over 100% is possible?

## Motivation

For people coming from blockchains it is not clear how referenced/confirmation rate over 100% is possible in a DAG

## Requirements

Write a list of what you want this feature to do.

1. small (i) icon near the referenced/confirmation rate
2. insert a description of how a referenced/confirmation rate over 100% is possible
3. show it when mouse pointer hover

## Are you planning to do it yourself in a pull request?

No

**Comment by msarcev** [comment]
Confirmation rate re-added on `main` branch and `stardust` with rate capped at 100%.
With https://github.com/iotaledger/explorer/issues/364.
