### ISSUE TITLE
[Bug]: Metadata text display

### ISSUE THREAD

**Issue by DRFGTO** [iotaledger/explorer#764]
### Issue description

Text within the transaction metadata splits text in the middle of words to fit within the text box.

### Expected behaviour

Text within the transaction metadata (contained within the text box) should spill onto the next line whist keeping each word whole. 

### Actual behaviour

Text within the transaction metadata splits text in the middle of words to fit within the text box.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

View a transaction on the explorer that has alot of text in its metadata such as: https://explorer.shimmer.network/shimmer/transaction/0xb0e57228c7fe10048a29bf4c393534370820a83a943a0bcb0b8a8f9f2285042b

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JannemanDev** [comment]
For example
![IMG_5035](https://user-images.githubusercontent.com/13236774/234058508-23086e26-9a64-4d58-a9d8-737187262ac5.jpeg)
