### ISSUE TITLE
[Task]: Release Explorer v3.2.0 

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#771]
### Task description

- Update in package.json
- Update changelog
- Release on github

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by brancoder** [comment]
[Release Explorer v3.2.0](https://github.com/iotaledger/explorer/releases/tag/v3.2.0)
