### ISSUE TITLE
"Daily active addresses" metric is not updated at the same time as the other metrics

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/explorer#779]
### Issue description

All metrics in the statistics page seem to be updated for "daily activity" at 0:00 UTC

The only metric that does not follow this is the "Daily active addresses" 

### Expected behaviour

Daily active addresses should be updated at the same time as all other metrics

### Actual behaviour

Daily active addresses seems to be updated at around 4 am UTC

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Just check the graphs in the statistics page between 0:00 UTC and 4 am UTC

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarcev** [comment]
Closing, As this is an issue in the Chronicle/Influx integration.
