### ISSUE TITLE
[Bug} HttpStatus: 500 for chrysalis-mainnet address

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#818]
https://explorer.iota.org/chrysalis-mainnet/addr/iota1qpr293apst6qp50flcyagh2qk3yyzjds0knc4djz3cfe55ek8zvsc998q5v returns 0 balance and no txs, even though there should be something.
Browser console reveals the issue is this request:
```
Request URL:
https://explorer-api.iota.org/transactionhistory/chrysalis-mainnet/46a2c7a182f400d1e9fe09d45d40b4484149b07da78ab6428e139a533638990c
Request Method:
GET
Status Code:
400 Bad Request
```
where the response is
```
{
    "error": {
        "route": "addresses/ed25519/46a2c7a182f400d1e9fe09d45d40b4484149b07da78ab6428e139a533638990c/tx-history",
        "httpStatus": 500,
        "code": "500"
    }
}
```

**Comment by msarcev** [comment]
Found an issue that needs to be fixed in goldenDB

**Comment by begonaalvarezd** [comment]
The current chrysalis mainnet archive seems fixed, balances and tx history, please reopen if the issue pops again 🙏🏼
