### ISSUE TITLE
Align icons in Network Switch dropdown menu

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#82]
## Description

Network icons in dropdown menu are not aligned due to large description text for Mainnet network.
Linked to PR:  #80 

## Expected behaviour

Possible solution is to shorten the Mainnet description text so icons get aligned.

![image](https://user-images.githubusercontent.com/52735957/149367644-a9a8a0c0-ba65-46cc-b111-5fd7d4067d8c.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149366215-bd382e39-dfa6-457c-b12e-18dd226a0134.png)

**Comment by evavirseda** [comment]
Resolved
