### ISSUE TITLE
Remove FiatSelector icon from search input field

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#83]
## Bug description

Icon ChevronDownGray from FiatSelector is visible in search input field for viewport desktop-down. 
Linked to: #80 

## Actual behaviour

Possible solution is to fix the z-index of the ChevronDownGray icon.

![image](https://user-images.githubusercontent.com/52735957/149368994-3fedaa97-5801-485e-ac03-586bf4b01c38.png)

**Comment by evavirseda** [comment]
Resolved
