### ISSUE TITLE
[Task]: Improve first load experience

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#834]
### Task description

Due to the switch to using the WASM based IOTA SDK, users visting the explorer for the first time will be seeing a white page until the blob has been downloaded (can take a 1-2 seconds on first load). This most likely will bounce users from the site or be perceived as a slow site.

Therefore take into consideration to show some rendered elements before the WASM IOTA SDK is downloaded. Either try to render simply the normal elements or show a loader.

### Requirements

There is a clear indiciation that the explorer is working and doing something.

### Acceptance criteria

It is clear to the user that something is happening and just needs to wait a small amount of time.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
We could simply add a loader so the user at least knows that something is happening.
If its not too much trouble, we could display basic elements like the navnar & the footer, and show the loading in between, but just if its an easy thing to do, otherwise just display the loader
