### ISSUE TITLE
Show Market Cap amount in abbreviated form with symbols

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#84]
## Bug description

Show Market Cap value in abbreviated form with symbols (billion – B ex. 2.14B ).
Linked to: #80 

## Expected behaviour

![image](https://user-images.githubusercontent.com/52735957/149370116-de0ba031-87bd-4022-b469-bf78a34f65c8.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149370230-58ca5112-3d86-46a8-9897-ea6752b582d3.png)

**Comment by laumair** [comment]
Fixed with https://github.com/iotaledger/explorer/pull/103
