### ISSUE TITLE
Change message payload type to uppercase for mobile view

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#85]
## Description

On the Landing page message payload type text is capitalized for mobile view. Change the text to uppercase for mobile view.
Linked to: #80 

## Expected behaviour

![image](https://user-images.githubusercontent.com/52735957/149512933-f73ebb88-5eaf-481c-ae33-cd1290c372d2.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149512586-f5d4041b-cb61-463f-8ad9-3ff9d8d277ec.png)

**Comment by rubalv96** [comment]
Resolved
