### ISSUE TITLE
[Task]: Improve readability of Address Transaction History

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#857]
### Task description

Rework the Transaction history to be less about the output and more about Transactions!

We want to go from this format:
![image](https://github.com/iotaledger/explorer/assets/6864498/464ba84f-b30c-436b-9a6a-1473bfea9899)
to a standard, more human readable, bank statement style.

The columns should be:
**Date, TransactionId,  (+/-) Change in base token value**

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Blocked by  https://github.com/iotaledger/inx-chronicle/issues/1313
