### ISSUE TITLE
Transaction Message: align transaction payload values

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#86]
## Bug description

Transaction payload section values are not aligned on the Transaction Message page.
Linked to: #80 

## Expected behaviour

Transaction payload values should be aligned.

![image](https://user-images.githubusercontent.com/52735957/149516289-8cd2d6a9-7cf8-4495-aa0a-d62d457313ea.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149516600-62d2188b-f952-4beb-8923-ef51028272aa.png)

**Comment by rubalv96** [comment]
Resolved
