### ISSUE TITLE
Transaction Message: remove Value from General section

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#87]
## Description

Value of transaction is shown in General section on Transaction message page.  Transaction value should not be shown in General section.
Linked to: #80 

## Expected behaviour

![image](https://user-images.githubusercontent.com/52735957/149522011-d7fa45d3-62d9-40a5-a24b-3cb305e9a077.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149517946-3ec223ee-f692-4457-b91a-31bce37be35d.png)

**Comment by begonaalvarezd** [comment]
@brancoder is the expected behavior taken from figma? I believe `Balance` is a typo from figma and doesnt belong to a value transaction. We do use balance in the address page
