### ISSUE TITLE
Transaction Message: add Balance to General section

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#88]
## Bug description

Balance is not shown in General section on Transaction message page. Balance should be shown in General section.
Linked to: #80 

## Expected behaviour

![image](https://user-images.githubusercontent.com/52735957/149522471-0f3984bd-c91b-4103-9c74-3c34d985f410.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149522561-804e5395-9ef5-46af-969e-e1b0c955f406.png)

**Comment by begonaalvarezd** [comment]
https://github.com/iotaledger/explorer/issues/87#issuecomment-1013229303
