### ISSUE TITLE
Address page: add Final Balance icon

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#89]
## Description

Final Balance icon is missing in General section on Address page.

## Expected behaviour

Final Balace icon should be shown  in general section.

![image](https://user-images.githubusercontent.com/52735957/149523461-da92a362-8e8e-4f03-b784-9f80439fd11e.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149523773-7a924c66-4fdc-4a57-8086-2d4717cdf47a.png)

**Comment by rubalv96** [comment]
Resolved
