### ISSUE TITLE
Footer: Align footer--content columns for mobile view

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#91]
## Bug description

Footer content row columns are not aligned correctly for some devices (ex. Iphone 12 Pro).
Linked to: #80

## Expected behaviour

Footer content columns should be aligned 2 items per row

#Tested on:
iPhone 11 Pro Max
OS - iOS, v14.0
Browser - Safari
Screen Size - 6.5 in - 5.90 in x 2.72 in
Resolution - 1242 x 2688 px
Viewport - 414 x 896 dp
Aspect Ratio - 19.5 : 9 

![image](https://user-images.githubusercontent.com/52735957/149528194-e6f4b413-0c66-4e9b-9040-42a1fdf0c248.png)

## Actual behaviour

3 Items are shown in first row and 1 in the second

#Tested on: 
iPhone 12 Pro
Chrome browser simulator
Resolution - 1170 x 2532 px
Viewport - 390  x 844 dp

![image](https://user-images.githubusercontent.com/52735957/149531732-08d70d33-ece3-467a-82d7-74103088c459.png)

**Comment by evavirseda** [comment]
Resolved
