### ISSUE TITLE
Message page: adjust sections bottom padding

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#92]
## Bug description

Padding between  all sections (General, Transaction payload, Indexation payload, Metadata) and the horizontal divider line do not correspond to designs.
Linked to: #80 

## Expected behaviour

Adjust padding-bottom between all sections (General, Transaction payload, Indexation payload, Metadata) and the horizontal divider line to correspond to designs.

![image](https://user-images.githubusercontent.com/52735957/149538431-e01e9233-bb36-471d-b24c-1d107108524b.png)

## Actual behaviour

<img width="156" alt="Untitled" src="https://user-images.githubusercontent.com/52735957/149541140-e1379192-39de-4783-a17d-536dc4da7d89.png">

**Comment by evavirseda** [comment]
Resolved
