### ISSUE TITLE
[Task]: Improve release process

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#923]
### Task description

At the moment, the release process is manual, but we should improve it
- On every merge to `dev`: release staging automatically
- On a production version tag pushed (v.*) (without `beta` or `alpha`) in the version number
    - update docker images to use the pushed tagged version (client & api), so that everybody can update their docker images too
    - update the servers to use the pushed tagged version (client & api) 

Additionally, production releases should automatically draft a release in github, the automatic changelog can come later on, no need for now, we should just draft a release with the right name and version

### Requirements

Above mentioned

### Acceptance criteria

Above mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Dr-Electron** [comment]
Lovely. Would be great to have a major.minor tag which I can use in the sandbox so I get all patch updates automatically. We do that everywhere else too

**Comment by begonaalvarezd** [comment]
This task was split into multiple

**Comment by Dr-Electron** [comment]
Can you mention this issue in the new issues or mention the other issues here?

**Comment by begonaalvarezd** [comment]
List of the multiple tasks it was split into
- https://github.com/iotaledger/explorer/issues/1008
- https://github.com/iotaledger/explorer/issues/1009
- https://github.com/iotaledger/explorer/issues/1013
- https://github.com/iotaledger/explorer/issues/1010
- https://github.com/iotaledger/explorer/issues/1011
- https://github.com/iotaledger/explorer/issues/1012

@Dr-Electron fyi
