### ISSUE TITLE
[Bug]: Available Balance incorrect on foundation address

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/explorer#925]
### Issue description

The available balance shown at the foundation's address from the supply increase is incorrect.

https://explorer.iota.org/mainnet/addr/iota1qp8h9augeh6tk3uvlxqfapuwv93atv63eqkpru029p6sgvr49eufyz7katr?tab=Transactions

### Expected behaviour

It should show the available balance stemming from the outputs which are available (not timelocked anymore)

### Actual behaviour

It shows 715302.14 IOTA being available even though there are at least 4 outputs which are no longer time locked and are not yet spent amounting to a total >11266259.4 IOTAs.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
@panteleymonchuk the problem seems to be on the chronicle endpoint, `sigLockedBalance` is not "available balance" but rather something like `is_trivial_unlock` which is not very useful, we are discussing with the chronicle team to decide on a solution

**Comment by begonaalvarezd** [comment]
Blocked by https://github.com/iotaledger/inx-chronicle/issues/1312
