### ISSUE TITLE
[Task]: Fix nova sdk setup for Linux

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#928]
### Task description

the sed commands we have in `setup_nova.sh` dont seem to work in Linux
eg `sed -i '' '2s/.*/    \"name\": \"@iota\/sdk-nova\",/' package.json`, so we should try to fix it to make it work for all OS

### Requirements

`setup_nova.sh` fixed for Linux

### Acceptance criteria

Above mentioned

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by shufps** [comment]
Mario got a workflow from me for compiling the iota-sdk bindings. It also fixes the `sed`s :blush:
