### ISSUE TITLE
Address page: adjust sections bottom padding

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#93]
## Bug description

Padding between all sections (General, Transaction payload) and the horizontal divider line do not correspond to designs.
Linked to: #80

## Expected behaviour

Adjust padding-bottom between all sections (General, Transaction payload) and the horizontal divider line to correspond to designs.

![image](https://user-images.githubusercontent.com/52735957/149542175-8617cb8b-8b29-45e0-9099-c6269e138005.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149542096-7027ae46-cd41-496d-9b52-2a410a600221.png)

**Comment by evavirseda** [comment]
Resolved
