### ISSUE TITLE
Transaction Message:  remove transaction value from Transaction payload section for mobile view 

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#94]
## Bug description

Value of transaction is shown in Transaction payload section for mobile view.
Linked to: #80

## Expected behaviour

Hide transaction value for mobile view. 

![image](https://user-images.githubusercontent.com/52735957/149769770-75e5061c-53d7-4e5f-bf27-60b8246a0430.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149769668-589c366d-4973-42da-bbd9-80091d95145e.png)

**Comment by evavirseda** [comment]
Resolved
