### ISSUE TITLE
[Bug]: Redirecting to Address page with a preselected tab sporadically fails 

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/explorer#949]
### Issue description

When redirecting to the Address page from the search with a preselected tab the app sometimes fails to display the preselected tab. 
Unsure if this could also happen when deeplinking the tab from outside the explorer.

### Expected behaviour

The app displays the correct tab every time.

### Actual behaviour

Sporadically the app loses the parameter and shows the default tab.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

1. Open Address Page (e.g.: https://explorer.iota.org/testnet/addr/rms1ppyx34shww5l3e28gynp5r5zljyru2vuyc2vjjeyqr3yy02vtwlx52sh4rj?tab=DID)
2. Repeatedly search for the same DID (`did:iota:rms:0x4868d61773a9f8e54741261a0e82fc883e299c2614c94b2400e2423d4c5bbe6a`)
3. Observe the page changing to the state tab at some point

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
I can replicate the issue, the redirection to the `?tab=DID` url is not triggered on random situations, thanks for the report
