### ISSUE TITLE
Landing page: change Payload type color for mobile view

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#95]
## Bug description

Payload type color for mobile view is $grey-6 #677695. 
Linked to: #80

## Expected behaviour

Change payload type color for mobile view to Grayscale/Gray 3 #D8E1F4.

![image](https://user-images.githubusercontent.com/52735957/149905754-32fb81ea-a440-4701-a2c0-a989bd2f4797.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149906461-00d750f0-1c15-4541-8a43-baa5b58be245.png)

**Comment by evavirseda** [comment]
Resolved

**Comment by brancoder** [comment]
Latest changes to payload type color for mobile view to Grayscale/Gray 3 #D8E1F4 also changed color for larger viewports.

##Expected behaviour

Change payload type color to Grayscale/Gray 5 #909FBE for larger viewports

![image](https://user-images.githubusercontent.com/52735957/149913987-5a3724a5-cc6b-460f-9962-f7eeaf4df9ed.png)

##Actual behaviour

![image](https://user-images.githubusercontent.com/52735957/149914149-c1cfdbe5-4b66-4fba-bb2c-560a25136b2a.png)

**Comment by evavirseda** [comment]
Right, it is now fixed
