### ISSUE TITLE
[Improvement UX]: Hide or collapse tabs that are empty on the Alias Output page

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/explorer#950]
### Issue description

When loading an Alias Output view the tabs that actually do not contain any item, for instance foundries or native tokens, etc.) they could be hidden or collapsed in an elegant manner . 

This is specially critical for Alias that are just DIDs which the other tabs are going to be usually empty ... 

### Expected behaviour

Hidden tabs or collapsed

### Actual behaviour

All tabs are shown

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Load an alias output that is just a DID

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmcanterafonseca-iota** [comment]
![Screenshot 2024-01-11 at 09 57 20](https://github.com/iotaledger/explorer/assets/67736750/14e8e71e-9950-448e-9fca-f06da772a0c7)

**Comment by eike-hass** [comment]
To give a little context: If DIDs are used in tandem with on-chain assets (identifying the minter of NFTs, adding a DID to your main "Account") more tabs would be active. Just to clarify that not all DIDs will be this "empty".

**Comment by begonaalvarezd** [comment]
Lets go for hiding the tabs that are not needed
