### ISSUE TITLE
[Task]: Improve the intial load speed of the page regarding wasm

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#965]
### Task description

There are already two wasm files loading on `dev` branch (sdk + identity wasm) and after nova there will be potentialy two more (sdk-nova etc...).

- Look into a way to speed up the "initial page load", be it with lazy loading of wasms depending on Landing network or anything else that would help

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
For me sometimes it takes really long to load (sometimes even over a minute, not sure what's going on there, maybe a local problem), but I also get this in the browser console logged:
```
index-c25614d4.js:23 `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
 ```
