### ISSUE TITLE
[Bug] Address page: Two children with the same key

### ISSUE THREAD

**Issue by brancoder** [iotaledger/explorer#97]
## Bug description

On Address page in transactions history table there is an issue when encountering two children with the same key. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
Linked to: #80 

## Steps To reproduce the bug

1. [Visit address link](https://explorer-balvarez-boxfish-studio.vercel.app/mainnet/addr/iota1qqkupta4xalh2qa4gkmr4lw5dz2xw5fx8jx32nwzkt4d0auy0kluv7qrhc5)
2.  Wait until history transactions are loaded

## Expected behaviour

Children keys should be unique.

## Actual behaviour

Transaction with the same `messageId: 0001e440bb755743a2884ed5b15db0ce5c1defc5e49da80ab5b15a9599a2e891` is displayed twice

![image](https://user-images.githubusercontent.com/52735957/150343456-91b621ba-cb2b-4de5-9d00-7eacf4902e67.png)

## Errors

![image](https://user-images.githubusercontent.com/52735957/150343318-809de0c6-951d-4841-a592-880e5995e036.png)

**Comment by begonaalvarezd** [comment]
@brancoder We are investigating this issue, seems to be a problem with the new chronicle endpoint. It is returning duplicated records and conflicting transactions

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/170
